// Textos fixos de interpretação para Sol, Lua, Ascendente e aspectos.
// Linguagem acolhedora, focada em personalidade e propósito de vida.
// Cada texto tem entre 80 e 120 palavras. Nada de travessões.

export const SUN_TEXTS: Record<string, string> = {
  "Áries":
    "Você é uma alma feita pra começar. O Sol em Áries acende em você uma vontade de agir antes de pensar muito, de abrir caminhos onde outros ainda hesitam. Aprende sobre si mesma fazendo, errando, recomeçando. Quando se cala demais, perde o fio; quando se permite liderar, encontra propósito. Pode ter pavio curto e ficar impaciente com processos lentos, mas dentro dessa pressa mora uma coragem rara, daquelas que inspiram quem está perto. Sua missão é manter a chama acesa sem queimar tudo no caminho, lembrar que continuar também é forma de coragem, e que iniciar com amor multiplica o brilho do começo.",
  "Touro":
    "Você é da turma que constrói. O Sol em Touro te dá uma identidade firmada no que dura, no que se planta com calma e floresce no tempo certo. Seu propósito está em criar valor, raiz e prazer pra você e pra quem ama. Aprende sobre si mesma cuidando do corpo, da casa, das pequenas rotinas que viram afeto. Pode resistir demais a mudanças e segurar relações ou trabalhos só por medo de perder o que já firmou, mas quando confia, sua presença vira chão. Sua missão é se valorizar sem precisar provar nada, lembrar que merecer e desfrutar também fazem parte de viver bem.",
  "Gêmeos":
    "Você é feita de muitas. O Sol em Gêmeos te coloca aqui pra conectar pessoas, ideias e mundos diferentes, e cada conversa te ensina um pouco mais sobre quem você é. Aprende perguntando, lendo, observando, mudando de opinião sem culpa. Pode se sentir dispersa, com vontade de fazer tudo ao mesmo tempo, e às vezes parece difícil escolher um caminho só. Seu propósito não é caber numa única gaveta. Sua missão é honrar essa curiosidade que te move, escolher onde colocar foco sem se trair, e usar sua leveza pra traduzir o mundo pra quem precisa entender melhor o que sente.",
  "Câncer":
    "Você sente em camadas profundas. O Sol em Câncer te dá uma identidade construída no cuidado, na memória afetiva e no sentido de pertencer. Seu propósito mora nos vínculos: família, amizades, casa, raízes. Aprende sobre si mesma cuidando dos outros e percebendo, com o tempo, que também merece o mesmo carinho. Pode oscilar entre acolher demais e se proteger fechando a concha, especialmente quando se sente exposta. Sua missão é construir um lar dentro de você primeiro, pra que o afeto seja escolha, não falta. Quando se permite essa segurança interna, sua sensibilidade vira força que abraça o mundo inteiro.",
  "Leão":
    "Você nasceu pra brilhar. O Sol em Leão te dá uma identidade calorosa, criativa e expressiva, e seu propósito está em ser autenticamente vista e em inspirar quem está perto. Aprende sobre si mesma se permitindo aparecer, ocupar palco, criar com o coração. Pode cair na armadilha de depender de aplauso e se machucar quando o reconhecimento demora, mas a luz que você carrega não precisa de plateia pra existir. Sua missão é confiar no próprio valor mesmo no silêncio, dividir generosidade sem perder o centro, e lembrar que liderar de verdade é alumiar o caminho dos outros também.",
  "Virgem":
    "Você é uma alma de cuidado fino. O Sol em Virgem te dá uma identidade construída pelo serviço, pela análise e pelo desejo sincero de fazer bem feito. Aprende sobre si mesma melhorando o que toca, e seu propósito está em ajudar com competência e presença, dos detalhes às grandes entregas. Pode se cobrar demais, ficar presa numa exigência que ninguém pediu e esquecer de celebrar o quanto já caminhou. Sua missão é aceitar a própria humanidade, perceber que perfeição não é meta, é prisão, e que o seu olhar atento já é, por si só, uma forma rara de amar o mundo.",
  "Libra":
    "Você é feita pra criar pontes. O Sol em Libra constrói sua identidade a partir do encontro: você se descobre nas relações, nas trocas e na busca por harmonia. Seu propósito mora em criar beleza, justiça e equilíbrio onde antes havia tensão. Aprende sobre si mesma ouvindo o outro e percebendo, aos poucos, o que é seu de verdade. Pode evitar conflito a ponto de calar a própria voz, e isso te custa caro. Sua missão é cultivar relações que te enxerguem inteira, escolher a si também na hora de equilibrar a balança, e lembrar que dizer não com leveza também é gesto de amor.",
  "Escorpião":
    "Você é uma alma de profundidade. O Sol em Escorpião te dá uma identidade que se forma nas crises, nos recomeços e nas verdades que ninguém quer encarar. Seu propósito está em transformar, em transmutar o que pesa em força. Aprende sobre si mesma mergulhando, sentindo tudo, atravessando o que assusta. Pode confundir intensidade com controle, segurar mágoa por muito tempo, ou se proteger atrás de mistério. Sua missão é confiar onde for seguro confiar, deixar a vulnerabilidade ser parte da sua força, e usar essa percepção rara que você tem pra curar, ao invés de armar, os caminhos por onde passa.",
  "Sagitário":
    "Você é uma alma em busca. O Sol em Sagitário te dá uma identidade expansiva, filosófica e aventureira, e seu propósito está em descobrir sentido e dividir esse sentido com o mundo. Aprende viajando, lendo, conversando com quem pensa diferente, e cada experiência amplia o que você acredita. Pode prometer mais do que entrega, fugir quando a vida pede compromisso, ou se apegar demais à própria verdade. Sua missão é honrar essa fome de horizonte sem perder o agora, abraçar a inteireza dos próprios desejos e usar seu otimismo natural pra acender luz em quem caminha junto, com generosidade e sem dogma.",
  "Capricórnio":
    "Você veio pra construir. O Sol em Capricórnio te dá uma identidade firmada na disciplina, na responsabilidade e na conquista que vem com o tempo. Seu propósito está em deixar marca concreta, em criar algo que dure. Aprende sobre si mesma assumindo desafios, errando, ajustando o passo. Pode carregar peso a mais, achar que precisa segurar tudo sozinha e esquecer que descanso também é parte do caminho. Sua missão é entender que seu valor não está só no que entrega, lembrar de aproveitar o trajeto e não só a chegada, e deixar que afeto e leveza também tenham lugar na agenda da vida.",
  "Aquário":
    "Você é uma alma de futuro. O Sol em Aquário te dá uma identidade original, independente e voltada pra algo maior do que você sozinha. Seu propósito está em inovar, em pertencer sem se diluir, em ajudar grupos a enxergarem possibilidades novas. Aprende sobre si mesma questionando, rompendo padrões e criando seu próprio jeito de existir. Pode parecer distante quando se protege com a razão, e às vezes cisma de estar sempre meio fora do esquadro. Sua missão é abraçar essa diferença sem virar ilha, deixar afeto entrar, e usar sua visão de futuro pra construir, no presente, comunidades onde dá pra ser livre junto.",
  "Peixes":
    "Você é uma alma fluida. O Sol em Peixes te dá uma identidade sensível, empática e profundamente conectada ao invisível. Seu propósito está em traduzir o que sente em arte, cuidado ou espiritualidade, e em lembrar o mundo de que existe algo maior costurando tudo. Aprende sobre si mesma se entregando, e também aprendendo, com o tempo, onde termina você e começa o outro. Pode se perder na dor alheia ou se desligar da realidade quando ela pesa demais. Sua missão é cultivar limites doces, criar espaços de silêncio pra se reencontrar, e confiar que sua sensibilidade é dom, não fragilidade.",
};

export const MOON_TEXTS: Record<string, string> = {
  "Áries":
    "Sua Lua em Áries sente de uma vez só. As emoções chegam intensas, rápidas, e querem ser expressadas no mesmo instante. Você precisa de movimento, de estímulo e de independência pra se sentir bem, e fica sufocada quando alguém tenta te conter. Pode reagir antes de entender, dizer coisas no calor e se cobrar depois, mas sua honestidade emocional é um presente: você não esconde o que sente. Sua missão afetiva é aprender a pausar antes de explodir, escolher onde colocar essa coragem, e lembrar que cuidar de si também é uma forma de proteger quem te ama de respostas que doem mais do que precisariam.",
  "Touro":
    "Sua Lua em Touro precisa de chão. Você se sente bem quando tem rotina, comida boa, abraço demorado, lugares onde o tempo passa mais devagar. As emoções chegam firmes e mudam pouco, então quando você ama, ama por muito tempo, e quando se machuca, demora a soltar. Pode se apegar a relações ou hábitos só pela segurança, e resistir a mudanças mesmo quando elas seriam um alívio. Sua missão afetiva é cultivar segurança dentro de você, não só fora, perceber que o conforto também pode ser reinventado, e deixar que o prazer entre na vida sem culpa, como linguagem natural do seu coração.",
  "Gêmeos":
    "Sua Lua em Gêmeos sente pensando. Você processa o que vive falando, escrevendo, conversando, e precisa colocar em palavras pra entender o que está acontecendo por dentro. As emoções mudam de cor com facilidade, e sua mente busca variedade e estímulo pra se sentir viva. Pode racionalizar demais o que sente, evitar profundidade emocional virando piada ou trocando de assunto. Sua missão afetiva é encontrar pessoas com quem dá pra falar de verdade, e aprender a ficar com o sentimento mesmo quando ele não cabe numa frase pronta. O silêncio também é linguagem, e seu coração tem coisas que só ele sabe.",
  "Câncer":
    "Sua Lua em Câncer está em casa. Você sente em profundidade, guarda memórias afetivas com riqueza de detalhes e cria laços que duram. Precisa de aconchego, de pertencimento e de pessoas com quem o coração possa pousar sem medo. Pode se fechar na concha quando se sente exposta, e ficar presa em situações antigas por puro apego ao que já foi. Sua missão afetiva é construir um lar interno onde você se acolhe primeiro, sem terceirizar essa segurança. Quando você se permite essa base, sua intuição vira bússola, e o cuidado que oferece deixa de pesar pra virar oferta livre, generosa.",
  "Leão":
    "Sua Lua em Leão pede calor. Você precisa de afeto expressado, de reconhecimento sincero e de pessoas que te enxerguem com brilho nos olhos. Quando se sente amada, derrete em generosidade; quando se sente esquecida, dói fundo. Suas emoções são dramáticas no melhor sentido: vívidas, presentes, sem meio termo. Pode confundir amor com aplauso e cobrar dos outros uma constância que ninguém entrega o tempo todo. Sua missão afetiva é aprender a se aplaudir primeiro, criar uma relação carinhosa com o próprio coração, e perceber que o amor verdadeiro também vive nos gestos pequenos, no silêncio compartilhado, na presença que não precisa de palco.",
  "Virgem":
    "Sua Lua em Virgem sente cuidando. Você expressa afeto sendo útil, organizando, antecipando o que o outro precisa antes mesmo que ele perceba. Precisa de ordem, de rotina e de pequenas certezas pra se sentir em paz, e ansiedade aparece quando algo fica solto. Pode reprimir o que sente por achar que não tem espaço, ou se cobrar uma maturidade que ninguém pediu. Sua missão afetiva é aprender a receber tanto quanto oferece, deixar que cuidem de você sem precisar merecer, e perceber que sentir bagunça às vezes faz parte de ser humana. Você não precisa estar perfeita pra ser amada.",
  "Libra":
    "Sua Lua em Libra busca harmonia. Você se sente bem quando os ambientes estão equilibrados, quando as pessoas se entendem, quando há beleza ao redor. Precisa de companhia e de relações pra processar o que vive, e quase sempre adapta o que sente pra manter a paz. Pode evitar conflito a ponto de não saber o que de fato quer, e ficar à mercê das opiniões alheias. Sua missão afetiva é construir uma voz interna firme, perceber que discordar também é forma de cuidado, e cultivar relações onde você pode aparecer inteira, sem precisar lapidar o sentimento pra caber no que o outro espera.",
  "Escorpião":
    "Sua Lua em Escorpião sente fundo. Você não tem como amar pela metade, e o que mexe com você mexe com tudo. Tem uma intuição quase telepática, percebe o que ninguém diz e guarda segredos como cofre. Pode confundir intensidade com controle, segurar mágoa por muito tempo, ou testar quem está perto antes de confiar. Sua missão afetiva é escolher onde gastar essa profundidade, perceber que vulnerabilidade não te fragiliza, e deixar que algumas pessoas atravessem suas camadas sem precisar merecer cada degrau. Quando você confia de verdade, sua presença transforma quem ama, e sua paixão vira força que cura, não que aprisiona.",
  "Sagitário":
    "Sua Lua em Sagitário precisa de horizonte. Você sente bem quando tem liberdade pra ir e vir, quando a vida tem aventura, quando as conversas têm sentido maior. Reage ao mundo com otimismo e humor, e às vezes usa essa leveza pra não encarar o que dói. Pode fugir da profundidade emocional trocando de cenário, e prometer presença que não consegue sustentar. Sua missão afetiva é deixar de escapar quando o sentimento aperta, perceber que ficar também é forma de coragem, e construir vínculos que te dão raiz sem te tirar asa. Liberdade verdadeira nasce quando o coração escolhe, não quando ele foge.",
  "Capricórnio":
    "Sua Lua em Capricórnio aprendeu cedo a se segurar. Você tende a controlar o que sente, a parecer firme mesmo quando por dentro está em pedaços, e a se cobrar uma maturidade que talvez tenha vindo antes do tempo. Precisa de estrutura e de pessoas confiáveis pra baixar a guarda. Pode reprimir afeto por achar que mostrar é fraqueza, e se isolar quando o mundo pesa. Sua missão afetiva é se permitir colo, pedir ajuda sem culpa e aprender que sua sensibilidade não te tira a força, ela te torna inteira. Vulnerabilidade, no tempo certo, é o que firma os vínculos que duram.",
  "Aquário":
    "Sua Lua em Aquário pensa o que sente. Você processa emoções com certo distanciamento, prefere entender o que está acontecendo antes de mergulhar, e precisa de espaço dentro dos vínculos pra não se sentir engaiolada. É leal de um jeito raro com quem considera família escolhida. Pode parecer distante quando se protege com a razão, ou se assustar com emoções intensas que não obedecem lógica. Sua missão afetiva é descer do mirante e sentir, mesmo quando o sentimento bagunça o sistema, e perceber que pertencer não significa perder liberdade. Você pode ter vínculo profundo e singularidade no mesmo coração, sem abrir mão de nenhum.",
  "Peixes":
    "Sua Lua em Peixes absorve tudo. Você sente o ambiente, capta o humor das pessoas antes mesmo que falem, e às vezes confunde o que é seu com o que é do outro. Precisa de silêncio, de arte, de momentos de retiro pra se reencontrar. Sua empatia é vasta, sua intuição é fina, sua sensibilidade é espiritual. Pode se perder na dor alheia ou idealizar pessoas que não estão à altura do seu carinho. Sua missão afetiva é cultivar limites doces, criar pausas pra te recarregar e lembrar que cuidar de si não é egoísmo, é o que te permite continuar sendo essa fonte rara.",
};

export const ASC_TEXTS: Record<string, string> = {
  "Áries":
    "Com Ascendente em Áries, você chega no mundo de cabeça erguida e passo firme. As pessoas te percebem como decidida, enérgica e direta, mesmo nos dias em que por dentro você está incerta. Tem facilidade pra começar coisas e uma presença que ocupa espaço sem pedir licença. Pode parecer impaciente ou impulsiva pra quem não te conhece bem, mas há uma coragem rara na forma como você encara desafios. Seu jeito de existir no mundo é a porta de entrada pro seu propósito: agir, abrir caminho, inspirar movimento. Sua missão é canalizar essa força com presença, escolhendo onde liderar com o coração inteiro, não só com pressa.",
  "Touro":
    "Com Ascendente em Touro, você atravessa o mundo com calma e firmeza. Sua presença passa segurança, beleza e um certo aconchego que faz as pessoas quererem ficar perto. Age com cautela, gosta de sentir as coisas antes de decidir, e tem um jeito muito próprio de saborear cada gesto. Pode parecer lenta ou inflexível pra quem corre demais, mas a sua resistência é justamente o que firma quem está ao seu redor. Sua maneira de existir no mundo é uma forma de cuidado discreto. Sua missão é honrar esse ritmo sem deixar o medo de mudança travar o que precisa florescer.",
  "Gêmeos":
    "Com Ascendente em Gêmeos, você chega com leveza e curiosidade. As pessoas te enxergam como comunicativa, ágil, antenada em mil assuntos ao mesmo tempo. Aborda a vida pelo diálogo e pela observação, e tem uma facilidade rara de transitar entre mundos diferentes. Pode parecer dispersa ou um pouco superficial pra quem não vê o quanto sua mente está sempre conectando pontos. Seu jeito de existir é uma ponte: você liga pessoas, ideias e possibilidades. Sua missão é escolher onde colocar foco sem se trair, perceber que profundidade também combina com você, e usar sua palavra com a leveza e o cuidado que ela merece.",
  "Câncer":
    "Com Ascendente em Câncer, você chega ao mundo com afeto nos olhos. As pessoas sentem em você um acolhimento que faz baixar a guarda, e muita gente confia logo de cara sem saber direito por quê. Tem um jeito intuitivo e protetor de agir, e às vezes recolhe na concha quando o ambiente te incomoda. Pode parecer reservada ou difícil de ler em alguns dias, mas isso é só o ciclo natural da sua sensibilidade. Sua maneira de existir é cuidar e ser cuidada. Sua missão é construir um lar dentro de você primeiro, pra que o acolhimento que oferece nunca te esvazie.",
  "Leão":
    "Com Ascendente em Leão, você entra num lugar e o lugar percebe. Sua presença é calorosa, magnética, expressiva, e mesmo quando você está quieta há algo solar no jeito como ocupa o espaço. Age com generosidade e tende a inspirar quem está perto. Pode parecer convicta demais ou um pouco dramática quando se sente ferida, e o desejo de ser vista é parte legítima da sua jornada. Sua maneira de existir é brilhar com inteireza. Sua missão é confiar nesse brilho mesmo sem aplauso externo, dividir o palco com carinho e lembrar que liderança verdadeira é também acender luz nos outros.",
  "Virgem":
    "Com Ascendente em Virgem, você chega de forma discreta, atenta e prestativa. Costuma observar antes de agir, percebe detalhes que ninguém mais vê e tem um jeito naturalmente competente de resolver o que aparece. As pessoas te enxergam como confiável e responsável, alguém em quem dá pra contar. Pode parecer crítica ou reservada à primeira vista, mas isso é só sua mente analítica trabalhando. Sua maneira de existir é um cuidado fino, quase artesanal. Sua missão é deixar que a vida tenha espaço pra ser imperfeita e bonita ao mesmo tempo, sem precisar consertar tudo pra se permitir descansar e ser amada.",
  "Libra":
    "Com Ascendente em Libra, você chega com elegância e diplomacia. Sua presença é harmoniosa, e as pessoas notam uma graça natural no jeito como você se comunica e se apresenta. Aborda a vida buscando equilíbrio, cuidando da estética, evitando arestas. Pode parecer indecisa quando quer agradar a todo mundo, ou um pouco distante quando se esquece do próprio centro. Sua maneira de existir é tecer relações com cuidado. Sua missão é manter a beleza sem perder a verdade, dizer o que pensa mesmo quando isso quebra a harmonia aparente, e construir vínculos onde você possa aparecer inteira, sem precisar de armadura de gentileza.",
  "Escorpião":
    "Com Ascendente em Escorpião, você chega com presença magnética e olhar que enxerga camadas. As pessoas sentem em você uma profundidade que intriga e às vezes intimida. Age com estratégia, observa muito antes de se entregar e protege sua intimidade com fechadura tripla. Pode parecer fechada ou difícil de decifrar, e isso é parte do seu mistério, não defeito. Sua maneira de existir é transformar tudo que toca. Sua missão é usar essa intensidade pra curar, não pra controlar, escolher com cuidado quem atravessa suas camadas e lembrar que mostrar vulnerabilidade, no momento certo, é o gesto mais corajoso que existe.",
  "Sagitário":
    "Com Ascendente em Sagitário, você chega com fé na vida. Sua presença é expansiva, otimista, com um quê de aventura que faz as pessoas quererem te ouvir. Aborda o mundo com entusiasmo e busca por significado, e tem uma facilidade rara de transformar o cotidiano em filosofia. Pode parecer exagerada ou um pouco descomprometida pra quem prefere certezas, mas seu otimismo é combustível pra quem caminha junto. Sua maneira de existir é abrir horizonte. Sua missão é honrar essa fome de mundo sem perder o agora, e perceber que aprofundar uma escolha também é forma de liberdade, não de prisão.",
  "Capricórnio":
    "Com Ascendente em Capricórnio, você chega com seriedade tranquila. As pessoas te percebem como madura, responsável e capaz, mesmo quando você ainda está descobrindo o caminho. Age com disciplina e planejamento, e tem uma autoridade natural que cresce com o tempo. Pode parecer reservada ou contida demais, e às vezes se sente mais velha do que a própria idade. Sua maneira de existir é construir, devagar e com peso. Sua missão é se permitir afrouxar o controle de vez em quando, deixar que afeto e diversão tenham espaço na rotina, e lembrar que descansar também faz parte da construção de uma vida sólida.",
  "Aquário":
    "Com Ascendente em Aquário, você chega diferente. Sua presença tem uma originalidade que se nota logo, e as pessoas te percebem como livre, inteligente e meio fora do esquadro do óbvio. Aborda a vida com curiosidade e independência, e gosta de quebrar padrões que não fazem sentido pra você. Pode parecer distante ou imprevisível pra quem espera convenção, mas essa autenticidade é justamente sua marca. Sua maneira de existir é desafiar o normal. Sua missão é não se esconder atrás do desapego, deixar afeto entrar mesmo quando bagunça o sistema, e usar sua visão de futuro pra criar pertencimento, não isolamento, ao seu redor.",
  "Peixes":
    "Com Ascendente em Peixes, você chega como névoa suave. Sua presença é etérea, empática, com um jeito quase camaleônico de se moldar ao ambiente. As pessoas sentem em você acolhimento e mistério ao mesmo tempo, e muitas projetam em você o que querem ver. Aborda o mundo de forma intuitiva, fluindo onde a corrente leva. Pode parecer difícil de definir ou um pouco perdida pra quem precisa de contornos firmes. Sua maneira de existir é dissolver fronteiras. Sua missão é manter um centro próprio dentro dessa fluidez, criar limites doces e confiar que sua sensibilidade é caminho, não obstáculo, pra encontrar seu lugar.",
};

// Interpretação geral de cada tipo de aspecto, em frase única.
export const ASPECT_GLOSS: Record<string, string> = {
  "Conjunção":
    "essas energias se fundem dentro de você e se amplificam, agindo quase como uma só voz.",
  "Sextil":
    "essas energias se complementam com leveza e abrem oportunidades quando você está atenta.",
  "Quadratura":
    "essas energias se tensionam e geram fricção, e é justamente nesse atrito que mora um dos seus maiores aprendizados.",
  "Trígono":
    "essas energias fluem com naturalidade e te entregam um talento que vem fácil, quase de graça.",
  "Quincúncio":
    "essas energias não se encaixam direito e pedem ajuste constante, um afinar fino ao longo da vida.",
  "Oposição":
    "essas energias vivem em polos opostos dentro de você, e o convite é integrar os dois lados em vez de pendular entre eles.",
};
