/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as AuthenticatedRitualzinhoRouteImport } from './routes/_authenticated/ritualzinho'
import { Route as AuthenticatedPlanoDeFundoRouteImport } from './routes/_authenticated/plano-de-fundo'
import { Route as AuthenticatedPiramideRouteImport } from './routes/_authenticated/piramide'
import { Route as AuthenticatedMapaAstralRouteImport } from './routes/_authenticated/mapa-astral'
import { Route as AuthenticatedCompletarPerfilRouteImport } from './routes/_authenticated/completar-perfil'
import { Route as AuthenticatedCeuHojeRouteImport } from './routes/_authenticated/ceu-hoje'
import { Route as AuthenticatedBaralhoCiganoRouteImport } from './routes/_authenticated/baralho-cigano'
import { Route as AuthenticatedMapaAstralIdRouteImport } from './routes/_authenticated/mapa-astral.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRitualzinhoRoute =
  AuthenticatedRitualzinhoRouteImport.update({
    id: '/ritualzinho',
    path: '/ritualzinho',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlanoDeFundoRoute =
  AuthenticatedPlanoDeFundoRouteImport.update({
    id: '/plano-de-fundo',
    path: '/plano-de-fundo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPiramideRoute = AuthenticatedPiramideRouteImport.update({
  id: '/piramide',
  path: '/piramide',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapaAstralRoute = AuthenticatedMapaAstralRouteImport.update({
  id: '/mapa-astral',
  path: '/mapa-astral',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompletarPerfilRoute =
  AuthenticatedCompletarPerfilRouteImport.update({
    id: '/completar-perfil',
    path: '/completar-perfil',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCeuHojeRoute = AuthenticatedCeuHojeRouteImport.update({
  id: '/ceu-hoje',
  path: '/ceu-hoje',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBaralhoCiganoRoute =
  AuthenticatedBaralhoCiganoRouteImport.update({
    id: '/baralho-cigano',
    path: '/baralho-cigano',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMapaAstralIdRoute =
  AuthenticatedMapaAstralIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMapaAstralRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/baralho-cigano': typeof AuthenticatedBaralhoCiganoRoute
  '/ceu-hoje': typeof AuthenticatedCeuHojeRoute
  '/completar-perfil': typeof AuthenticatedCompletarPerfilRoute
  '/mapa-astral': typeof AuthenticatedMapaAstralRouteWithChildren
  '/piramide': typeof AuthenticatedPiramideRoute
  '/plano-de-fundo': typeof AuthenticatedPlanoDeFundoRoute
  '/ritualzinho': typeof AuthenticatedRitualzinhoRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/mapa-astral/$id': typeof AuthenticatedMapaAstralIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/baralho-cigano': typeof AuthenticatedBaralhoCiganoRoute
  '/ceu-hoje': typeof AuthenticatedCeuHojeRoute
  '/completar-perfil': typeof AuthenticatedCompletarPerfilRoute
  '/mapa-astral': typeof AuthenticatedMapaAstralRouteWithChildren
  '/piramide': typeof AuthenticatedPiramideRoute
  '/plano-de-fundo': typeof AuthenticatedPlanoDeFundoRoute
  '/ritualzinho': typeof AuthenticatedRitualzinhoRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/': typeof AuthenticatedIndexRoute
  '/mapa-astral/$id': typeof AuthenticatedMapaAstralIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/baralho-cigano': typeof AuthenticatedBaralhoCiganoRoute
  '/_authenticated/ceu-hoje': typeof AuthenticatedCeuHojeRoute
  '/_authenticated/completar-perfil': typeof AuthenticatedCompletarPerfilRoute
  '/_authenticated/mapa-astral': typeof AuthenticatedMapaAstralRouteWithChildren
  '/_authenticated/piramide': typeof AuthenticatedPiramideRoute
  '/_authenticated/plano-de-fundo': typeof AuthenticatedPlanoDeFundoRoute
  '/_authenticated/ritualzinho': typeof AuthenticatedRitualzinhoRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/mapa-astral/$id': typeof AuthenticatedMapaAstralIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/baralho-cigano'
    | '/ceu-hoje'
    | '/completar-perfil'
    | '/mapa-astral'
    | '/piramide'
    | '/plano-de-fundo'
    | '/ritualzinho'
    | '/api/transcribe'
    | '/mapa-astral/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/baralho-cigano'
    | '/ceu-hoje'
    | '/completar-perfil'
    | '/mapa-astral'
    | '/piramide'
    | '/plano-de-fundo'
    | '/ritualzinho'
    | '/api/transcribe'
    | '/'
    | '/mapa-astral/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/baralho-cigano'
    | '/_authenticated/ceu-hoje'
    | '/_authenticated/completar-perfil'
    | '/_authenticated/mapa-astral'
    | '/_authenticated/piramide'
    | '/_authenticated/plano-de-fundo'
    | '/_authenticated/ritualzinho'
    | '/api/transcribe'
    | '/_authenticated/'
    | '/_authenticated/mapa-astral/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ritualzinho': {
      id: '/_authenticated/ritualzinho'
      path: '/ritualzinho'
      fullPath: '/ritualzinho'
      preLoaderRoute: typeof AuthenticatedRitualzinhoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plano-de-fundo': {
      id: '/_authenticated/plano-de-fundo'
      path: '/plano-de-fundo'
      fullPath: '/plano-de-fundo'
      preLoaderRoute: typeof AuthenticatedPlanoDeFundoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/piramide': {
      id: '/_authenticated/piramide'
      path: '/piramide'
      fullPath: '/piramide'
      preLoaderRoute: typeof AuthenticatedPiramideRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapa-astral': {
      id: '/_authenticated/mapa-astral'
      path: '/mapa-astral'
      fullPath: '/mapa-astral'
      preLoaderRoute: typeof AuthenticatedMapaAstralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/completar-perfil': {
      id: '/_authenticated/completar-perfil'
      path: '/completar-perfil'
      fullPath: '/completar-perfil'
      preLoaderRoute: typeof AuthenticatedCompletarPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ceu-hoje': {
      id: '/_authenticated/ceu-hoje'
      path: '/ceu-hoje'
      fullPath: '/ceu-hoje'
      preLoaderRoute: typeof AuthenticatedCeuHojeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/baralho-cigano': {
      id: '/_authenticated/baralho-cigano'
      path: '/baralho-cigano'
      fullPath: '/baralho-cigano'
      preLoaderRoute: typeof AuthenticatedBaralhoCiganoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapa-astral/$id': {
      id: '/_authenticated/mapa-astral/$id'
      path: '/$id'
      fullPath: '/mapa-astral/$id'
      preLoaderRoute: typeof AuthenticatedMapaAstralIdRouteImport
      parentRoute: typeof AuthenticatedMapaAstralRoute
    }
  }
}

interface AuthenticatedMapaAstralRouteChildren {
  AuthenticatedMapaAstralIdRoute: typeof AuthenticatedMapaAstralIdRoute
}

const AuthenticatedMapaAstralRouteChildren: AuthenticatedMapaAstralRouteChildren =
  {
    AuthenticatedMapaAstralIdRoute: AuthenticatedMapaAstralIdRoute,
  }

const AuthenticatedMapaAstralRouteWithChildren =
  AuthenticatedMapaAstralRoute._addFileChildren(
    AuthenticatedMapaAstralRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBaralhoCiganoRoute: typeof AuthenticatedBaralhoCiganoRoute
  AuthenticatedCeuHojeRoute: typeof AuthenticatedCeuHojeRoute
  AuthenticatedCompletarPerfilRoute: typeof AuthenticatedCompletarPerfilRoute
  AuthenticatedMapaAstralRoute: typeof AuthenticatedMapaAstralRouteWithChildren
  AuthenticatedPiramideRoute: typeof AuthenticatedPiramideRoute
  AuthenticatedPlanoDeFundoRoute: typeof AuthenticatedPlanoDeFundoRoute
  AuthenticatedRitualzinhoRoute: typeof AuthenticatedRitualzinhoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBaralhoCiganoRoute: AuthenticatedBaralhoCiganoRoute,
  AuthenticatedCeuHojeRoute: AuthenticatedCeuHojeRoute,
  AuthenticatedCompletarPerfilRoute: AuthenticatedCompletarPerfilRoute,
  AuthenticatedMapaAstralRoute: AuthenticatedMapaAstralRouteWithChildren,
  AuthenticatedPiramideRoute: AuthenticatedPiramideRoute,
  AuthenticatedPlanoDeFundoRoute: AuthenticatedPlanoDeFundoRoute,
  AuthenticatedRitualzinhoRoute: AuthenticatedRitualzinhoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
